### ISSUE TITLE
Support batch event submission

### ISSUE THREAD

**Issue by junglebarry** [talis/echo-php-client#15]
The client seems to submit a separate HTTP request per event. Can it support batching?

**Comment by markwallsgrove** [comment]
@junglebarry issues should be raised against https://github.com/talis/platform/issues. Raised issue https://github.com/talis/platform/issues/1644

**Comment by junglebarry** [comment]
Thanks @markwallsgrove, and sorry for raising in the wrong place!

**Comment by markwallsgrove** [comment]
No problem :)
